
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bankportal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankportal-ui
  template: 
    metadata:
      labels:
        app: bankportal-ui
    spec:
      containers:
        - name: bankportal-ui
          image: 'rianle/bankportal-ui:ocp4'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: nginx-conf # Mount the volume
            mountPath: /etc/nginx/conf.d/default.conf # Overwrite the default config
            subPath: default.conf # Use the key from the ConfigMap
      volumes:
      - name: nginx-conf # Define the volume from the ConfigMap
        configMap:
          name: angular-nginx-conf
