
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bankportal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankportal-api
  template: 
    metadata:
      labels:
        app: bankportal-api
    spec:
      containers:
        - name: bankportal-api
          image: 'rianle/bankportal-api:latest'
          ports:
            - containerPort: 8180
              protocol: TCP
          imagePullPolicy: IfNotPresent
          env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql:3306/bankingapp"
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-db-credentials
                key: DB_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-db-credentials
                key: DB_PASSWORD
